### ISSUE TITLE
bug: Very high false positive rate due to API key rate limiting

### ISSUE THREAD

**Issue by serg06** [jef/nvidia-snatcher#58]
### Description

I just got the script and tried it with this `.env`:

```
NOTIFICATION_TEST="false"
PAGE_TIMEOUT="30000"
RATE_LIMIT_TIMEOUT="5000"
STORES="nvidia"
```

Every 30 seconds (about every 5 requests) I get a false positive because the page returns `Rate limit exceeded for API_KEY [9485fa7b159e42edb08a83bde0d83dia]`. (Confirmed this by looking at the screenshot it took.)

### Possible solution

Ignore the page when it says "Rate limit exceeded". Maybe print a warning to console too.

**Comment by geman220** [comment]
Could fix if we decied to use the bandaid in #50 .  Let me know and I'll get it added.

**Comment by jef** [comment]
Fixed in #54.

**Comment by serg06** [comment]
Issue is not fixed, still happening (but very rarely at the moment). Exact same problem.

Here's the commit I'm on:

```
C:\repo\nvidia-snatcher>git log -n 1
commit 3b2ba29cf1c90bdfc98f3d3a042160a6d9c9601f (HEAD -> main, origin/main, origin/HEAD)
Author: Gylfi <gylli251@gmail.com>
Date:   Sat Sep 19 15:23:49 2020 +0000

    chore(store): add bandh links (#65)

    Co-authored-by: Jef LeCompte <jeffreylec@gmail.com>
```

And here's a screenshot that gets generated:

![success-1600537744120](https://user-images.githubusercontent.com/1350889/93685729-6e819c80-fa7f-11ea-8f37-404ebf9d376b.png)

**Comment by andrewmackrodt** [comment]
Closing as the implementation described is no longer in use.
